/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Canonical operational snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CanonicalSnapshot"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a browser profile-administration session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description HttpOnly session cookie issued */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid administrator token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Administrator authentication is not configured */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the browser profile-administration session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session cleared */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/isolation-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Safe desired host bridge-isolation policy snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IsolationPolicy"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server-sent transition events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/wireguard/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profile lifecycle and redacted metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfileManagementStatus"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProfileWrite"];
                };
            };
            responses: {
                /** @description Encrypted staged revision */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Administrator token required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Mutation disabled or origin rejected */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Candidate invalid */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/wireguard/profiles/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProfileWrite"];
                };
            };
            responses: {
                /** @description Redacted candidate metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RedactedProfile"];
                    };
                };
                /** @description Administrator token required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Line-specific safe validation errors */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/wireguard/profiles/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Stage a structured edit; omitted secret fields preserve the active stored value */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        private_key?: string | null;
                        addresses: string[];
                        dns: string[];
                        listen_port: number | null;
                        mtu: number | null;
                        peers: Record<string, never>[];
                    };
                };
            };
            responses: {
                /** @description Encrypted staged revision with redacted metadata */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid structured edit */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Administrator token required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/wireguard/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Transactionally activate the explicitly selected mounted or GUI-managed source */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {unknown} */
                        source: "mounted" | "gui_managed";
                    };
                };
            };
            responses: {
                /** @description Safe apply and rollback result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Administrator token required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Source activation failed and was rolled back or left fail closed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/wireguard/profiles/{revision}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    revision: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Safe apply and rollback result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Administrator token required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Apply failed; previous profile restored or traffic blocked */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/wireguard/profiles/{revision}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    revision: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Inactive revision deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Active or missing revision */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Administrator token required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/settings/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Masked GUI-managed Omnihook settings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationSettingsView"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NotificationSettingsInput"];
                };
            };
            responses: {
                /** @description Saved masked Omnihook settings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationSettingsView"];
                    };
                };
                /** @description Invalid notification settings */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/settings/notifications/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Test notification delivered */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Test notification delivery failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/history/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from_unix_ms?: number;
                    to_unix_ms?: number;
                    bucket_seconds?: number;
                    usage_id?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description App-owned per-workload usage history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsageHistoryResponse"];
                    };
                };
                /** @description Invalid bounded history query */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Local history database unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/history/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from_unix_ms?: number;
                    to_unix_ms?: number;
                    before_id?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated safe operational event history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventHistoryResponse"];
                    };
                };
                /** @description Invalid bounded history query */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Local history database unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/history/vpn-server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from_unix_ms?: number;
                    to_unix_ms?: number;
                    bucket_seconds?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description App-owned WireGuard endpoint latency history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VpnServerHistoryResponse"];
                    };
                };
                /** @description Invalid bounded history query */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Local history database unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prometheus text exposition for current per-client traffic counters */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProfileWrite: {
            /** @description Complete WireGuard profile; never returned */
            profile: string;
        };
        /** @description Bounded parsed metadata; contains no private or preshared key values */
        RedactedProfile: {
            interface: {
                private_key_configured?: boolean;
                addresses?: string[];
                dns?: string[];
                listen_port?: number | null;
                mtu?: number | null;
            };
            peers: Record<string, never>[];
            peer_count: number;
            ipv4_full_tunnel: boolean;
            full_tunnel_peer: number | null;
            warnings: Record<string, never>[];
            /** @enum {unknown} */
            apply_kind: "no_change" | "dns_reload" | "sync_conf" | "sync_conf_and_routes" | "tunnel_recycle";
        };
        ProfileManagementStatus: {
            /** @enum {unknown} */
            lifecycle: "unconfigured" | "validating" | "applying" | "active" | "degraded" | "apply_failed" | "recovering";
            /** @enum {unknown} */
            source: "mounted" | "gui_managed";
            source_mutable: boolean;
            active_revision: string | null;
            active: components["schemas"]["RedactedProfile"] | null;
            revisions: Record<string, never>[];
            last_apply: Record<string, never> | null;
            management_available: boolean;
            mutation_authorized: boolean;
            ipv4_only: boolean;
        };
        LoginRequest: {
            token: string;
        };
        NotificationSettingsView: {
            enabled: boolean;
            /** @enum {unknown} */
            provider: "discord" | "slack" | "telegram" | "generic";
            destination: string | null;
            webhook_configured: boolean;
            telegram_chat_id_configured: boolean;
            hmac_secret_configured: boolean;
            timeout_seconds: number;
            rtt_threshold_ms: number;
            alert_stack_started: boolean;
            alert_vpn_disconnected: boolean;
            alert_vpn_reconnected: boolean;
            alert_rtt_above_threshold: boolean;
            alert_diagnostic_failed: boolean;
            updated_at_unix_ms: number;
        };
        NotificationSettingsInput: {
            enabled: boolean;
            /** @enum {unknown} */
            provider: "discord" | "slack" | "telegram" | "generic";
            webhook_url: string;
            telegram_chat_id: string;
            hmac_secret: string;
            timeout_seconds: number;
            rtt_threshold_ms: number;
            alert_stack_started: boolean;
            alert_vpn_disconnected: boolean;
            alert_vpn_reconnected: boolean;
            alert_rtt_above_threshold: boolean;
            alert_diagnostic_failed: boolean;
        };
        CanonicalSnapshot: {
            /** @constant */
            schema_version: 2;
            sequence: number;
            generated_at_unix_ms: number;
            /** @enum {unknown} */
            protection: "enforced" | "unknown" | "violated";
            /** @enum {unknown} */
            availability: "starting" | "healthy" | "degraded" | "unavailable" | "recovering";
            checks: {
                [key: string]: components["schemas"]["SubsystemCheck"];
            };
            transitions: components["schemas"]["Transition"][];
            port_forward: components["schemas"]["PortForwardStatus"];
            recovery: Record<string, never>;
            external_probe: components["schemas"]["ExternalProbeResult"];
            vpn_server: components["schemas"]["VpnServerStatus"];
            isolation_policy: components["schemas"]["IsolationPolicy"];
            topology: Record<string, never>;
            clients: {
                [key: string]: components["schemas"]["ClientState"];
            };
            traffic: Record<string, never>;
            profile_management: components["schemas"]["ProfileManagementStatus"];
        };
        ExternalProbeResult: {
            /** @enum {unknown} */
            status: "unknown" | "healthy" | "degraded" | "unavailable";
            observed_at_unix_ms: number | null;
            source_public_non_tailscale: boolean | null;
            source_matches_claimed_ip: boolean | null;
            tcp_port_reachable: boolean | null;
            forwarded_port: number | null;
            lease_acquired_at_unix_ms: number | null;
            request_started_at_unix_ms: number | null;
            reason_code: string | null;
            safe_message: string | null;
        };
        VpnServerStatus: {
            configured_endpoint_host: string | null;
            configured_endpoint_port: number | null;
            configured_address_family: string | null;
            allowed_ips_posture: string;
            runtime_endpoint_address: string | null;
            runtime_endpoint_port: number | null;
            provider_inferred: string | null;
            region_inferred: string | null;
            inference_source: string | null;
            inference_confidence: string | null;
            active: boolean;
            latest_handshake_unix: number | null;
            handshake_age_seconds: number | null;
            observed_at_unix_ms: number | null;
            latency: components["schemas"]["VpnServerLatency"];
        };
        VpnServerLatency: {
            /** @enum {unknown} */
            status: "measured" | "timeout" | "unsupported" | "resolution_failed" | "unavailable";
            sampled_at_unix_ms: number | null;
            latest_rtt_ms: number | null;
            recent_min_rtt_ms: number | null;
            recent_average_rtt_ms: number | null;
            recent_max_rtt_ms: number | null;
            loss_ratio: number | null;
            sample_count: number;
        };
        PortForwardStatus: {
            /** @enum {unknown} */
            phase: "disabled" | "waiting_for_target" | "requested" | "leased" | "installed" | "verified" | "target_ambiguous" | "lease_lost" | "install_failed" | "verification_failed" | "unavailable";
            requested_target: string | null;
            internal_port: number | null;
            external_port: number | null;
            tcp_udp_agree: boolean | null;
            lease_acquired_at_unix_ms: number | null;
            lease_expires_at_unix_ms: number | null;
            dnat_installed: boolean;
            externally_verified: boolean | null;
            change_sequence: number;
            changed_at_unix_ms: number | null;
        };
        ClientState: {
            container_id: string;
            usage_id: string;
            /** @enum {unknown} */
            usage_id_source: "explicit_label" | "compose_service" | "container_lifetime";
            name: string;
            /** Format: ipv4 */
            ipv4_address: string;
            port_forward_target: boolean;
            target_port: number | null;
            compliant: boolean;
            compliance_message: string;
            running: boolean;
            ipv6_address: string | null;
            networks: string[];
            port_forward_label_valid: boolean;
            route_intent: components["schemas"]["RouteIntentState"];
            traffic: components["schemas"]["ClientTrafficState"];
        };
        RouteIntentState: {
            /** @enum {unknown} */
            status: "verified" | "mismatch" | "unknown";
            ipv4_default_network: string | null;
            ipv6_default_network: string | null;
            egress_gateway_priority: number | null;
            gateway_priorities: {
                [key: string]: number | null;
            };
            reason_code: string;
            safe_message: string;
        };
        ClientTrafficState: {
            download_packets: number;
            downloaded_bytes: number;
            upload_packets: number;
            uploaded_bytes: number;
            sampled_at_unix_ms: number | null;
            history: components["schemas"]["ClientTrafficSample"][];
        };
        ClientTrafficSample: {
            sampled_at_unix_ms: number;
            downloaded_bytes: number;
            uploaded_bytes: number;
        };
        UsageHistoryResponse: {
            from_unix_ms: number;
            to_unix_ms: number;
            bucket_seconds: number;
            points: components["schemas"]["UsageHistoryPoint"][];
            truncated: boolean;
        };
        UsageHistoryPoint: {
            bucket_start_unix_ms: number;
            usage_id: string;
            /** @enum {unknown} */
            usage_id_source: "explicit_label" | "compose_service" | "container_lifetime";
            name: string;
            download_bytes: number;
            upload_bytes: number;
            download_packets: number;
            upload_packets: number;
            sample_count: number;
        };
        EventHistoryResponse: {
            events: components["schemas"]["HistoricalEvent"][];
            next_before_id: number | null;
        };
        HistoricalEvent: {
            id: number;
            timestamp_unix_ms: number;
            /** @enum {unknown} */
            kind: "transition" | "port_forward";
            component: string;
            from_status: string | null;
            to_status: string | null;
            reason_code: string;
            safe_message: string;
            external_port: number | null;
            port_forward_phase: string | null;
        };
        VpnServerHistoryResponse: {
            from_unix_ms: number;
            to_unix_ms: number;
            bucket_seconds: number;
            points: components["schemas"]["VpnServerHistoryPoint"][];
            truncated: boolean;
        };
        VpnServerHistoryPoint: {
            bucket_start_unix_ms: number;
            configured_endpoint_host: string;
            runtime_endpoint_address: string;
            runtime_endpoint_port: number;
            active_sample_count: number;
            sample_count: number;
            measured_sample_count: number;
            minimum_rtt_ms: number | null;
            average_rtt_ms: number | null;
            maximum_rtt_ms: number | null;
        };
        IsolationPolicy: {
            /** @constant */
            schema_version: 1;
            generated_at_unix_ms: number;
            network: string;
            bridge: string;
            subnet: string;
            eligible_for_enforcement: boolean;
            reason_code: string;
            safe_message: string;
            issues: string[];
            participants: components["schemas"]["IsolationParticipant"][];
        };
        IsolationParticipant: {
            container_id: string;
            name: string;
            isolation_id: string | null;
            /** Format: ipv4 */
            ipv4_address: string;
            allowances: components["schemas"]["IsolationAllowance"][];
        };
        IsolationAllowance: {
            destination_id: string;
            /** Format: ipv4 */
            destination_address: string;
            port: number;
            /** @enum {unknown} */
            protocol: "tcp" | "udp";
        };
        SubsystemCheck: {
            id: string;
            /** @enum {unknown} */
            status: "pending" | "healthy" | "degraded" | "failed" | "unknown";
            /** @enum {unknown} */
            impact: "critical" | "advisory" | "optional";
            observed_at_unix_ms: number;
            changed_at_unix_ms: number;
            reason_code: string;
            safe_message: string;
            consecutive_failures: number;
        };
        Transition: {
            sequence: number;
            timestamp_unix_ms: number;
            component: string;
            from_status: string;
            to_status: string;
            reason_code: string;
            safe_message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
